### ISSUE TITLE
Scripts?

### ISSUE THREAD

**Issue by jundengdeng** [kcyu2014/smsop#1]
Hi Kaicheng,

It's very interesting to read the paper, entitled  _**Statistically Motivated Second Order Pooling**_. I would like to try to use it for my own research. Can you please share the code? Thanks! If it's not ready, I would appreciate it if you can share the the pooling layer by email. 

Thanks and best,
Jun

**Comment by Hellomodo** [comment]
Hi Kaicheng,

Could you also share the  code of the pooling layer with me by email?

Thanks

**Comment by kcyu2014** [comment]
Thanks for your interests, I am currently cleaning the code right now and will publish the code as soon as I can. Please contact me via kaicheng.yu@epfl.ch and I would provide the first version of my layer implemented in tensorflow/keras.

**Comment by zimenglan-sysu-512** [comment]
hi @kcyu2014 
do you still have a plan to release your code?

**Comment by kcyu2014** [comment]
@zimenglan-sysu-512 

Yes, the plan is to release before mid October. I am currently involved in another project, sorry for the delay.

**Comment by kcyu2014** [comment]
Due to the unexpected schedule of my late 2018, I again apologize for the delay of code-release. I have quickly clean the implementation and put it in the `snapshot` folder, consisting the final architecture I am using in all of my experiments. Please kindly check. 
The complete version will be released after CVPR deadline.

Cheers,
Kaicheng
